---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:

  - name: Добавить пользователя 'cloudru' 
    user:
      name: cloudru
      password: "$6$mysecretsalt$mn6E/B9o/DxKh7R.ltiRG29eyXkpBAb1bcDlkD9ClwsBAGc6dwjk4qaXFhRjLMobESUXYXLOs32tixnfzfpkl0"
  - name: Disable Root Login adn enable PubkeyAuthentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
  - lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PubkeyAuthentication'
      line: "PubkeyAuthentication yes"
    become: yes
    notify:
      - restart ssh
  - name: Установить authorized key из файла id_rsa.pub
    authorized_key:
      user: cloudru 
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfrfE0OluoNHb5dOpV4RpWmVXvMBWc17kaM7DDjCm7romNQMDX95i5Fc67Q3c47pvrm/qi/ZqsCeqNdLl5+VV41rVz701Pj/UUr2FZpIm80Ur0iM1DFy81GKo/lS1INopqdd4KvUnM2d8yqfJSm9m5Cq7AM9S0mqObuMayfqNR4YcOlm9fnEMqhrSWbBVvdghPNiBzs7T9RzEq/0w8rs743tCF7MICv72fdgYadrGlxFsFWSujwZXQLI4VUSxKirJBCUgfR0u84gZK/wUzJ4EPqMichniTf24AsvidozUHWMDmQ+pUaBTyxjD5egi8LcV0EHH4feHwzacA2gyGbOtFK3wpa/dgE1yvPTkPKnccIXKnbel0mfxfsBVkclc5/DnczmrdaGrX5DCrQbI+HO4lhr4KzAm/pw6qfLcw8KjCdVKsnCRXykdat8KUwNAeolknRWdKDqdsbyXBj+ePMTlMR8YmoBj9znYWwOnAAyu56utiteL0oq9YPkb7ZGF5ZOE="

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted